"""vote

Revision ID: 37a0a22ba351
Revises: 7a319345a0c1
Create Date: 2023-06-06 20:52:48.744261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a0a22ba351'
down_revision = '7a319345a0c1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote', sa.Integer(), nullable=False, server_default='0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_column('vote')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('vote')

    # ### end Alembic commands ###
