"""empty message

Revision ID: ff0b830b93b2
Revises: a3e333deb229
Create Date: 2023-05-28 21:09:42.233960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0b830b93b2'
down_revision = 'a3e333deb229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
